from httpx import AsyncClient

from tests.conftest import TEMPLE_LAT, TEMPLE_LON


async def test_marathi_facility_question_returns_nearby_water(client: AsyncClient) -> None:
    response = await client.post(
        "/api/conversation/message",
        json={
            "text": "जवळ पाणी कुठे मिळेल?",
            "location": {"lat": TEMPLE_LAT, "lon": TEMPLE_LON},
        },
    )
    assert response.status_code == 200

    body = response.json()
    assert body["intent"] == "facility"
    assert body["language"] == "mr"
    assert body["source"] == "rules"  # LLM disabled in tests
    assert body["data"]["facilities"], "expected at least one seeded facility"
    assert body["data"]["facilities"][0]["facility_type"] == "water"
    assert any(a["type"] == "show_facilities" for a in body["actions"])


async def test_hindi_is_detected_from_message(client: AsyncClient) -> None:
    response = await client.post(
        "/api/conversation/message", json={"text": "दर्शन का समय क्या है?"}
    )
    assert response.status_code == 200

    body = response.json()
    assert body["language"] == "hi"
    assert body["intent"] == "temple"


async def test_facility_question_without_location_asks_for_it(client: AsyncClient) -> None:
    response = await client.post(
        "/api/conversation/message", json={"text": "Where is the nearest toilet?"}
    )
    assert response.status_code == 200

    body = response.json()
    assert body["language"] == "en"
    assert body["data"]["missing_location"] is True
    assert "location" in body["reply"].lower()


async def test_sos_flow_requires_confirmation_then_dispatches(client: AsyncClient) -> None:
    raised = await client.post(
        "/api/conversation/message",
        json={
            "text": "मदत करा, इथे एक माणूस बेशुद्ध पडला आहे",
            "location": {"lat": TEMPLE_LAT, "lon": TEMPLE_LON},
        },
    )
    assert raised.status_code == 200

    body = raised.json()
    assert body["intent"] == "sos"
    assert body["requires_sos_confirmation"] is True
    # Emergency wording is deterministic — never generated by the model.
    assert body["source"] == "rules"
    assert any(a["type"] == "confirm_sos" for a in body["actions"])

    session_id = body["session_id"]
    confirmed = await client.post(
        "/api/conversation/sos/confirm",
        json={
            "session_id": session_id,
            "confirmed": True,
            "emergency_type": "medical",
            "location": {"lat": TEMPLE_LAT, "lon": TEMPLE_LON},
        },
    )
    assert confirmed.status_code == 200

    payload = confirmed.json()
    assert payload["confirmed"] is True
    assert payload["sos"]["status"] == "dispatched"
    assert payload["sos"]["eta_minutes"] >= 3
    assert "112" in payload["sos"]["helpline_numbers"]


async def test_sos_can_be_cancelled(client: AsyncClient) -> None:
    raised = await client.post(
        "/api/conversation/message", json={"text": "help me, emergency!"}
    )
    session_id = raised.json()["session_id"]

    response = await client.post(
        "/api/conversation/sos/confirm",
        json={"session_id": session_id, "confirmed": False},
    )
    assert response.status_code == 200

    body = response.json()
    assert body["confirmed"] is False
    assert body["sos"] is None


async def test_session_is_reused_across_turns(client: AsyncClient) -> None:
    first = await client.post("/api/conversation/message", json={"text": "नमस्कार"})
    session_id = first.json()["session_id"]

    second = await client.post(
        "/api/conversation/message",
        json={"text": "मंदिरात किती गर्दी आहे?", "session_id": session_id},
    )
    assert second.status_code == 200
    assert second.json()["session_id"] == session_id
    assert second.json()["intent"] == "crowd"


async def test_empty_message_is_rejected(client: AsyncClient) -> None:
    response = await client.post("/api/conversation/message", json={"text": "   "})
    assert response.status_code == 422
